[project]
name = "hevy-mcp"
version = "0.1.0"
description = "An MCP to interact with Hevy Public API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.1",
]
